# Generated by Django 4.2.7 on 2024-01-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitsa', '0003_activity_news_image1_alter_activity_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('income', models.TextField()),
                ('expenses', models.TextField()),
                ('image', models.ImageField(upload_to='Income_expenses_images/')),
            ],
        ),
    ]
