# Generated by Django 4.2.7 on 2024-01-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitsa', '0004_income_expenses'),
    ]

    operations = [
    ]
