# Generated by Django 4.2.10 on 2024-02-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitsa', '0005_auto_20240124_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_news',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
